networks:
  fairaccess:
    name: fairaccess
    external: true
  proxy:
    name: proxy
    external: true

services:
  core:
    image: codeberg.org/fairaccess/fairaccess-core:0.0.32
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.core.rule=Host(`fairaccess.ch`)"
      - "traefik.http.routers.core.entrypoints=http,https"
      - "traefik.http.middlewares.redirect-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-https.redirectscheme.permanent=true"
      - "traefik.http.routers.core.middlewares=redirect-https"
      - "traefik.http.routers.core.tls=true"
      - "traefik.http.routers.core.tls.certresolver=letsencrypt"
      - "traefik.http.services.core.loadbalancer.server.port=3000"
    networks:
      - proxy
      - fairaccess
